// flow-typed signature: 198f22f9184d35f0af86813ee1c9509b
// flow-typed version: <<STUB>>/humanize-duration_v3.11.0/flow_v0.57.3

/**
 * This is an autogenerated libdef stub for:
 *
 *   'humanize-duration'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'humanize-duration' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'humanize-duration/humanize-duration' {
  declare module.exports: any;
}

// Filename aliases
declare module 'humanize-duration/humanize-duration.js' {
  declare module.exports: $Exports<'humanize-duration/humanize-duration'>;
}
