// flow-typed signature: 155ff49dd11ae5279978377f61daa52d
// flow-typed version: <<STUB>>/styled-components-spacing_v2.1.3/flow_v0.57.3

/**
 * This is an autogenerated libdef stub for:
 *
 *   'styled-components-spacing'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'styled-components-spacing' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'styled-components-spacing/dist/index' {
  declare module.exports: any;
}

declare module 'styled-components-spacing/dist/Margin' {
  declare module.exports: any;
}

declare module 'styled-components-spacing/dist/Padding' {
  declare module.exports: any;
}

declare module 'styled-components-spacing/dist/sizes' {
  declare module.exports: any;
}

// Filename aliases
declare module 'styled-components-spacing/dist/index.js' {
  declare module.exports: $Exports<'styled-components-spacing/dist/index'>;
}
declare module 'styled-components-spacing/dist/Margin.js' {
  declare module.exports: $Exports<'styled-components-spacing/dist/Margin'>;
}
declare module 'styled-components-spacing/dist/Padding.js' {
  declare module.exports: $Exports<'styled-components-spacing/dist/Padding'>;
}
declare module 'styled-components-spacing/dist/sizes.js' {
  declare module.exports: $Exports<'styled-components-spacing/dist/sizes'>;
}
