// flow-typed signature: d6c225a9604e106796f6412c2854d582
// flow-typed version: <<STUB>>/truncate_v2.0.0/flow_v0.57.3

/**
 * This is an autogenerated libdef stub for:
 *
 *   'truncate'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'truncate' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'truncate/test' {
  declare module.exports: any;
}

declare module 'truncate/truncate' {
  declare module.exports: any;
}

// Filename aliases
declare module 'truncate/test.js' {
  declare module.exports: $Exports<'truncate/test'>;
}
declare module 'truncate/truncate.js' {
  declare module.exports: $Exports<'truncate/truncate'>;
}
